name: Run All Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  buildAndTest:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 20
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '20'

      - name: Build and Test
        run: |
          nohup gradle bootRun -Dspring.profiles.active=test > app.log 2>&1 &
          sleep 50
          gradle test