name: Run All Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup JDK 20
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '20'
      - name: Build Gradle
        run: gradle bootRun -Dspring.profiles.active=test &
      - name: Wait for the application to start
        run: sleep 10
      - name: Run  Tests
        run: gradle test