name: Run All Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 20
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '20'

      - name: Build Gradle
        run: ./gradlew build

  tests:
    needs: build
    runs-on: ubuntu-latest

    services:
      h2:
        console:
          enabled: true
        image: h2database/h2:latest
        ports:
          - 1521:1521

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 20
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '20'

      - name: Start application with H2 and test profile
        run: ./gradlew bootRun -Dspring.profiles.active=test

      - name: Display Contents of application-test.properties
        run: cat src/test/resources/application-test.properties

      - name: Wait for the application to start
        run: sleep 30

      - name: Run RegisterAndLogin Tests
        run: ./gradlew test --tests com.example.todoz.e2e.tests.separed_tests:RegisterAndLoginTestingChrome

      - name: Run UserCase Tests
        run: ./gradlew test --tests com.example.todoz.e2e.tests.whole_project_tests:UserCaseTestingChromeWhole

      - name: Run WeekReview Tests
        run: ./gradlew test --tests com.example.todoz.services:WeekReviewTesting
