name: Run E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build Gradle
        run: ./gradlew build

  tests:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Start the application
        run: ./gradlew bootRun

      - name: Wait for the application to start
        run: sleep 30

      - name: Run RegisterAndLogin Tests
        run: ./gradlew test --tests com.example.todoz.e2e.tests.separed_tests:RegisterAndLoginTestingChrome

      - name: Run UserCase Tests
        run: ./gradlew test --tests com.example.todoz.e2e.tests.whole_project_tests:UserCaseTestingChromeWhole

      - name: Run WeekReview Tests
        run: ./gradlew test --tests com.example.todoz.services:WeekReviewTesting

