name: Run All Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306
        env:
          MYSQL_USER: root
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: todoz
          MYSQL_HOST: 127.0.0.1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 20
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '20'

      - name: Build Gradle
        run: ./gradlew build

  tests:
    needs: build
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306
        env:
          MYSQL_USER: root
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: todoz
          MYSQL_HOST: 127.0.0.1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 20
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '20'

      - name: Wait for MySQL to be ready
        run: |
          sleep 15
          until nc -z -v -w30 localhost 3306
          do
            echo "Waiting for MySQL to be ready..."
            sleep 5
          done

      - name: Set MySQL environment variables for tests
        run: |
          echo "mysql.host=localhost" >> $GITHUB_ENV
          echo "mysql.port=3306" >> $GITHUB_ENV
          echo "mysql.user=root" >> $GITHUB_ENV
          echo "mysql.password=password" >> $GITHUB_ENV
          echo "mysql.database=todoz" >> $GITHUB_ENV

      - name: Start application with SQL and test profile
        run: ./gradlew bootRun -Dspring.profiles.active=test -DMYSQL_HOST=localhost -DMYSQL_PORT=3306 -DMYSQL_DATABASE=todoz -DMYSQL_USER=root -DMYSQL_PASSWORD=password


      - name: Wait for the application to start
        run: sleep 30

      - name: Run RegisterAndLogin Tests
        run: ./gradlew test --tests com.example.todoz.e2e.tests.separed_tests:RegisterAndLoginTestingChrome

      - name: Run UserCase Tests
        run: ./gradlew test --tests com.example.todoz.e2e.tests.whole_project_tests:UserCaseTestingChromeWhole

      - name: Run WeekReview Tests
        run: ./gradlew test --tests com.example.todoz.services:WeekReviewTesting
