name: Run All Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - spring:
          datasource:
            url: jdbc:h2:mem:testdb
            driver-class-name: org.h2.Driver
            username: sa
            password: password
          h2:
            console:
              enabled: true
          jpa:
            hibernate:
              ddl-auto: update

      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup JDK 20
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '20'
      - name: Build Gradle
        run: ./gradlew bootRun -Dspring.profiles.active=test

  tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        run: ./gradlew test
